INSERT INTO `unit_kerja` (`uk_id`, `uk_name`, `created_date`)
VALUES
    ('1', 'Biro Pemerintahan dan Otda Setda Provinsi Maluku', NOW()),
    ('2', 'Biro Hukum dan Hak Asasi Manusia Setda Provinsi Maluku', NOW()),
    ('3', 'Biro Organisasi Setda Provinsi Maluku', NOW()),
    ('4', 'Biro Kesejahteraan Rakyat Setda Provinsi Maluku', NOW()),
    ('5', 'Biro Umum Setda Provinsi Maluku', NOW()),
    ('6', 'Biro Administrasi Pimpinan Setda Provinsi Maluku', NOW()),
    ('7', 'Biro Perekonomian Daerah Setda Provinsi Maluku', NOW()),
    ('8', 'Biro Administrasi Pembangunan dan Layanan Pengadaan Barang/Jasa Pemerintah Setda Provinsi Maluku', NOW()),
    ('9', 'Sekretariat Dewan Perwakilan Rakyat Daerah Provinsi Maluku', NOW()),
    ('10', 'Inspektorat Provinsi Maluku', NOW()),
    ('11', 'Dinas Pendidikan dan Kebudayaan Provinsi Maluku', NOW()),
    ('12', 'Dinas Kesehatan Provinsi Maluku', NOW()),
    ('13', 'Dinas Pekerjaan Umum dan Penataan Ruang Provinsi Maluku', NOW()),
    ('14', 'Dinas Perumahan dan Kawasan Pemukiman Provinsi Maluku', NOW()),
    ('15', 'Satuan Polisi Pamong Praja Provinsi Maluku', NOW()),
    ('16', 'Dinas Sosial Provinsi Maluku', NOW()),
    ('17', 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak Provinsi Maluku', NOW()),
    ('18', 'Dinas Ketahanan Pangan Provinsi Maluku', NOW()),
    ('19', 'Dinas Lingkungan Hidup Provinsi Maluku', NOW()),
    ('20', 'Dinas Kependudukan dan Pencatatan Sipil Provinsi Maluku', NOW()),
    ('21', 'Dinas Pemberdayaan Masyarakat dan Desa Provinsi Maluku', NOW()),
    ('22', 'Dinas Perhubungan Provinsi Maluku', NOW()),
    ('23', 'Dinas Komunikasi dan Informatika Provinsi Maluku', NOW()),
    ('24', 'Dinas Koperasi, Usaha Kecil dan Menengah Provinsi Maluku', NOW()),
    ('25', 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Provinsi Maluku', NOW()),
    ('26', 'Dinas Pemuda dan Olah Raga Provinsi Maluku', NOW()),
    ('27', 'Dinas Perpustakaan dan Kearsipan Provinsi Maluku', NOW()),
    ('28', 'Dinas Kelautan dan Perikanan Provinsi Maluku', NOW()),
    ('29', 'Dinas Pariwisata Provinsi Maluku', NOW()),
    ('30', 'Dinas Pertanian Provinsi Maluku', NOW()),
    ('31', 'Dinas Kehutanan Provinsi Maluku', NOW()),
    ('32', 'Dinas Energi dan Sumber Daya Mineral Provinsi Maluku', NOW()),
    ('33', 'Dinas Perindustrian dan Perdagangan Provinsi Maluku', NOW()),
    ('34', 'Dinas Tenaga Kerja dan Transmigrasi Provinsi Maluku', NOW()),
    ('35', 'Badan Perencanaan Pembangunan Daerah Provinsi Maluku', NOW()),
    ('36', 'Badan Pengelola Keuangan dan Aset Daerah Provinsi Maluku', NOW()),
    ('37', 'Badan Pendapatan Daerah Provinsi Maluku', NOW()),
    ('38', 'Badan Kepegawaian Daerah Provinsi Maluku', NOW()),
    ('39', 'Badan Pengembangan Sumber Daya Manusia Provinsi Maluku', NOW()),
    ('40', 'Badan Penanggulangan Bencana Daerah Provinsi Maluku', NOW()),
    ('41', 'Badan Kesatuan Bangsa dan Politik Provinsi Maluku', NOW()),
    ('42', 'Badan Pengelola Perbatasan Provinsi Maluku', NOW());