INSERT INTO `jabatan` (`jabatan_id`, `jabatan_name`, `jabatan_status`, `created_date`)
VALUES
    ('1', 'Kepala Dinas Pekerjaan Umum dan Penataan Ruang', 'active', NOW()),
    ('2', 'Plh. Kepala Dinas Pekerjaan Umum dan Penataan Ruang', 'active', NOW()),
    ('3', 'Plt. Kepala Dinas Pekerjaan Umum dan Penataan Ruang', 'active', NOW()),
    ('4', 'Sekretaris Dinas', 'active', NOW()),
    ('5', 'Kepala Sub Bagian Kepegawaian dan Umum', 'active', NOW()),
    ('6', 'Kepala Sub Bagian Perencanaan, Evaluasi dan Pelaporan', 'active', NOW()),
    ('7', 'Kepala Sub Bagian Keuangan dan Aset', 'active', NOW()),
    ('8', 'Kepala Bidang Sumber Daya Air', 'active', NOW()),
    ('9', 'Kepala Seksi Perencanaan dan Pengendalian SDA', 'active', NOW()),
    ('10', 'Kepala Seksi Operasi dan Pemeliharaan', 'active', NOW()),
    ('11', 'Kepala Seksi Pelaksanaan', 'active', NOW()),
    ('12', 'Kepala Bidang Bina Marga', 'active', NOW()),
    ('13', 'Kepala Seksi Perencanaan dan Pengendalian BM', 'active', NOW()),
    ('14', 'Kepala Seksi Pengembangan Prasana Jalan', 'active', NOW()),
    ('15', 'Kepala Seksi Pengembangan Prasarana Jembatan', 'active', NOW()),
    ('16', 'Kepala Bidang Cipta Karya', 'active', NOW()),
    ('17', 'Kepala Seksi Perencanaan dan Pengendalian CK', 'active', NOW()),
    ('18', 'Kepala Seksi Pengembangan Air Minum dan Penyehatan Lingkungan', 'active', NOW()),
    ('19', 'Kepala Seksi Penataan Bangunan dan Lingkungan Permukiman', 'active', NOW()),
    ('20', 'Kepala Bidang Jasa Konstruksi', 'active', NOW()),
    ('21', 'Kepala Seksi Pemberdayaan', 'active', NOW()),
    ('22', 'Kepala Seksi Pengawasan', 'active', NOW()),
    ('23', 'Kepala Bidang Tata Ruang', 'active', NOW()),
    ('24', 'Kepala Seksi Pengaturan dan Pembinaan', 'active', NOW()),
    ('25', 'Kepala Seksi Pengawasan dan Pengendalian', 'active', NOW()),
    ('26', 'Kepala Seksi Pelaksanaan dan Pertanahan', 'active', NOW()),
    ('27', 'Staf Pelaksana', 'active', NOW()),
    ('28', 'Staf Honorer', 'active', NOW());